### ISSUE TITLE
make default imagedataset have different behavior for train vs val/test modes

### ISSUE THREAD

**Issue by ibro45** [ganslate-team/ganslate#69]
in our projects we have completely separate datasets for this, the question here is if paired and unpaired ImageDatasets should have their valtest equivalents or just the same dataset class that handles different modes using `conf.mode`

**Comment by ibro45** [comment]
support for unpaired and paired. probably separate classes, `UnpairedImageDataset` and `PairedImageDataset`. and then they handle train val test infer modes.

**Comment by ibro45** [comment]
implement transforms in them

**Comment by cnmy-ro** [comment]
1. Implemented the `UnpairedImageDataset` and the `PairedImageDataset`. In unpaired tasks where paired val/test data is available, the `UnpairedImageDataset` will be used for training and the `PairedImageDataset` in val/test modes. In the latter, the user must specify the config without any random augmentation transforms. The cityscapes task is a nice example of this case. Check out its config files.

2. Renamed `get_transform()` function (that was used in the old `ImageDataset`) to `get_single_image_transform()`. Implemented a separate `get_paired_image_transform()` that works on A-B image pairs.  
    - Simplified the specification of the preprocess settings. 
    - Renamed certain variables for clarity. Also, `load_size` and `final_size` (previously `crop_size`) now take a tuple <h, w> instead of a single `int` scalar.  
    - Commented out certain transform cases since I thought they were either problematic (for eg. `scale_shortside`) or redundant (for eg. `random_trim`).

3. Tested everything on `horse2zebra` and `cityscapes` tasks.

**Comment by ibro45** [comment]
oh very nice! I like how you organized it so that you use PairedImageDataset for val/test of unpaired tasks when they have such val/test set
